server:
  port: 12002
  servlet:
    context-path: "/bp"

spring:
  application:
    name: bp
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://ip:port/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ip
      port: port
      password: password
      database: 0
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

mybatis-flex:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  producer:
    endpoints: ip:port
  push-consumer:
     endpoints: ip:port

logging:
  level:
    root: INFO